description: Mathis, artisan du web. Site internet personnalisé à prix libre. Facile et pas chère. blog – association – pme - évènement



# Website configurations
baseurl: "/"
url: "https://mathis-webartisan.netlify.com"
plugins:
  - jekyll-sitemap

collections:
  creations:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "creations"
    values:
      layout: "creations"
      optionnal-style: "/assets/style/creations.css"

sass:
    sass_dir: "assets/style/_sass"